Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 44, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'%02d'%month+'%02d'%daysmonth+'_201Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 44, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'%02d'%month+'%02d'%daysmonth+'_20170110.nc')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 44, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'%02d'%month+'%02d'%daysmonth+'_201/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsat/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsat/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsatTraceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 33, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'0101_20170110.nc')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsat/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsat70110.nc')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2016/dt_global_allsat_phy_l4_20160930_20170110.nc'
70110.nc')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 44, in <module>
    ncfile=Dataset(inputfiles+'dt_global_allsat_phy_l4_'+year+'%02d'%month+'%02d'%daysmonth+'_201_phy_l4_20170101_20170110.nc'
_phy_l4_20170101_20170110.nc'
_phy_l4_20170101_20170110.nc'
/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/v3-0/2017/dt_global_allsat_phy_l4_20170101_20170110.nc'
_phy_l4_20170101_20170110.nc'
v3-0/2016/dt_global_allsat_phy_l4_20160531_20170110.nc'
v3-0/2016/dt_global_allsat_phy_l4_20160731_20170110.nc'
70110.nc')
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/g/data/ua8/CMEMS_SeaLevel/_phy_l4_20170101_20170110.nc'
v3-0/2016/dt_global_allsat_phy_l4_20161130_20170110.nc'
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
Traceback (most recent call last):
  File "/home/156/jm5970/github/phd_source/trackeddy_utils/analysis_trackeddy/trackeddy_satellite.py", line 55, in <module>
    ,sfilter='uniform',sfsize=50,destdir='',physics='',diagnostics=False,pprint=False)
  File "/home/156/jm5970/github/trackeddy/trackeddy/tracking.py", line 859, in analyseddyzt
    eddytd=dict_eddyt(ii,eddz)
UnboundLocalError: local variable 'eddz' referenced before assignment
